linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    # - import
    - metalinter
    # - module
    - performance
    # - sql
    - style
    - test
    - unused
  disable:
    - depguard
    - err113
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - interfacebloat
    - ireturn
    - mnd
    - nlreturn
    - paralleltest
    - revive
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  stylecheck:
    initialisms: [ID]
