name: Build Native WebView Libraries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check.outputs.tag }}
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Check if tag already built
        id: check
        run: |
          tag=$(curl -s https://api.github.com/repos/webview/webview/tags | jq -r '.[0].name')
          echo "tag=$tag" >> $GITHUB_OUTPUT

          if [ -f embedded/VERSION.txt ] && grep -q "$tag" embedded/VERSION.txt; then
            echo "Already built version $tag"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: ${{ matrix.job.os }}-${{ matrix.job.arch }}
    needs: prepare
    if: needs.prepare.outputs.skip != 'true'
    runs-on: ${{ matrix.job.runs-on }}
    strategy:
      matrix:
        job:
          - os: linux
            arch: amd64
            runs-on: ubuntu-latest
            file: libwebview.a
          - os: linux
            arch: arm64
            runs-on: ubuntu-24.04-arm
            file: libwebview.a
          - os: darwin
            arch: amd64
            runs-on: macos-latest
            file: libwebview.a
            args: -D CMAKE_OSX_ARCHITECTURES=x86_64
          - os: darwin
            arch: arm64
            runs-on: macos-latest
            file: libwebview.a
            args: -D CMAKE_OSX_ARCHITECTURES=arm64
          - os: windows
            arch: amd64
            runs-on: windows-latest
            file: Release/webview_static.lib
            args: -A x64
          - os: windows
            arch: arm64
            runs-on: windows-latest
            file: Release/webview_static.lib
            args: -A ARM64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: webview/webview
          ref: ${{ needs.prepare.outputs.tag }}

      - name: Install dependencies
        if: matrix.job.os == 'linux'
        run: |
          sudo apt-get update 
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Configure and Build
        run: |
          cmake -B build -S . -D CMAKE_BUILD_TYPE=Release ${{ matrix.job.args }} \
            -D WEBVIEW_BUILD_SHARED_LIBRARY=OFF \
            -D WEBVIEW_BUILD_STATIC_LIBRARY=ON \
            -D WEBVIEW_BUILD_TESTS=OFF \
            -D WEBVIEW_BUILD_EXAMPLES=OFF \
            -D WEBVIEW_BUILD_DOCS=OFF \
            -D WEBVIEW_ENABLE_PACKAGING=OFF \
            -D WEBVIEW_ENABLE_CHECKS=OFF
          cmake --build build --config Release

      - name: Rename artifact
        run: cp build/core/${{ matrix.job.file }} ${{ matrix.job.os }}_${{ matrix.job.arch }}.syso

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job.os }}_${{ matrix.job.arch }}
          path: ${{ matrix.job.os }}_${{ matrix.job.arch }}.syso

  finalize:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.skip != 'true'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-webview
          sign-commits: true
          commit-message: 'feat: update webview to ${{ needs.prepare.outputs.tag }}'
          title: 'feat: update webview to ${{ needs.prepare.outputs.tag }}'
          body: This PR updates the embedded WebView native libraries to version ${{ needs.prepare.outputs.tag }}.
