name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CGO_ENABLED: '0'

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    name: Test
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libwebkit2gtk-4.1-0 xvfb

      - name: Check shared library dependencies
        if: matrix.runs-on == 'ubuntu-latest'
        run: ldd embedded/linux_amd64/libwebview.so

      - name: Check shared library dependencies
        if: matrix.runs-on == 'ubuntu-24.04-arm'
        run: ldd embedded/linux_arm64/libwebview.so

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        if: startsWith(matrix.runs-on, 'ubuntu') == false
        run: go test -v ./...

      - name: Run tests
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" go test -v ./...
